### PR TITLE
feat: disable metrics by default

### LINKED ISSUE #27: Disable metrics by default
By default, we want to only collect audit logs.

Go through all modules and make sure metrics are disabled by default. Will be adding a new variable to enable metrics if needed.

this is in reference to another [issue](https://github.com/equinor/terraform-baseline/issues/44)

### PR DESCRIPTION
**Pull request by kov117**

### CODE REVIEW

**Comment by kov117** [comment]
Test pass but the plan shows metric is still enabled

**Comment by hknutsen** [comment]
@kov117 Plan shows metrics being disabled for me:

```terraform
  # module.grafana.azurerm_monitor_diagnostic_setting.this will be created
  + resource "azurerm_monitor_diagnostic_setting" "this" {
      + id                             = (known after apply)
      + log_analytics_destination_type = (known after apply)
      + log_analytics_workspace_id     = (known after apply)
      + name                           = "audit-logs"
      + target_resource_id             = (known after apply)

      + enabled_log {
          + category = "GrafanaLoginEvents"
        }

      + metric {
          + category = "AllMetrics"
          + enabled  = false
        }
    }
```

**Comment by kov117** [comment]
Oh ? i must have looked at it wrong then ? or maybe i just misunderstood what i was looking at 🤔?

**Review by hknutsen — APPROVED** [review]

**Comment by kov117** [comment]
Just a quick reference, i looked at the log analytic diagnostic and not the diagnostic settings. But Henrik showed med and confirmed that the metrics was infact disabled 👍🏽 thus we can close and merge this PR

**Pull request merged**
